accent = "#2E7D4A"
cursor = "#59CF77"
foreground = "#59CF77"
background = "#0A0A08"
selection_foreground = "#000000"
selection_background = "#59CF77"

color0 = "#02160C"
color1 = "#3DA862"
color2 = "#59CF77"
color3 = "#6FE685"
color4 = "#2E7D4A"
color5 = "#4DB866"
color6 = "#2E7D4A"
color7 = "#59CF77"
color8 = "#02160C"
color9 = "#3DA862"
color10 = "#59CF77"
color11 = "#6FE685"
color12 = "#2E7D4A"
color13 = "#4DB866"
color14 = "#2E7D4A"
color15 = "#59CF77"
